### ISSUE TITLE
Blacklist BED file

### ISSUE THREAD

**Issue by matthewjohnrossi** [seqcode/chexmix#1]
Can we change the ChexMix input for the blacklist from .out to accepting a .bed? The current format is getting screwed up by our 2-micron tags because of the hyphen.

**Comment by naomiyamada** [comment]
I've added an option to exclude the blacklist using a bed file. The option can be specified with --excludebed \<path-to-bed-file>

The updated ChExMix v0.2 jar file can be downloaded here:

http://lugh.bmb.psu.edu/software/chexmix/chexmix_v0.2.jar
