### ISSUE TITLE
Inconsistent motif naming

### ISSUE THREAD

**Issue by WilliamKMLai** [seqcode/chexmix#2]
Motif naming is inconsistent with subtype naming.
For example for 3 subtypes, naming is: subtype 0,1,2
Motif naming is 1,2,3 in the chexmix.experiment.transfac file

I also believe that motif naming is unlinked to subtype naming. For example, if subtype 0 and 2 have motifs, but subtype 1 does not the motifs are labeled 1 and 2. So there is no easy way to link the raw PWM back to the subtypes reported in the HTML.

**Comment by naomiyamada** [comment]
I fixed them. Motifs in transfac file are now named according to subtype0, subtype1, etc.
